telegram:
  api:
    url: ${TELEGRAM_API_URL}
    chatId: ${TELEGRAM_CHAT_ID}

pachka:
  api:
    url: ${PACHKA_API_URL}
    token: ${PACHKA_TOKEN}
    entity_id: ${PACHKA_ENTITY_ID}

bamboo:
  deploymentIds:

    136446236: "TST01_Billing Center"
    136446242: "TST01_Policy Center"

    136446146: "TST04_Policy Center"
    136446144: "TST04_Billing Center"

    146702424: "TST06_Policy Center"
    146702413: "TST06_Billing Center"

    146702414: "TST09_Billing Center"
    146702425: "TST09_Policy Center"

    136446246: "PROD_Policy Center"
    136446240: "PROD_Billing Center"

    136446248: "TST01_Producer Engage"
    136446148: "TST04_Producer Engage"
    146702435: "TST06_Producer Engage"
    146702436: "TST09_Producer Engage"
    136446252: "PROD_Producer Engage"


spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}